In [1]:
from netCDF4 import Dataset as NetCDFFile
import numpy as np
from numpy import matlib
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib import colors
import xarray as xr
from numpy import meshgrid
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.font_manager import findfont, FontProperties
from mpl_toolkits.basemap import Basemap
import pandas as pd
import warnings
import pickle
warnings.filterwarnings("ignore")
font = findfont(FontProperties(family=['sans-serif']))
font

'/System/Library/Fonts/LucidaGrande.ttc'

In [14]:
EOF1 = open('EOF1.pkl','rb')
EOF1 = pickle.load(EOF1)
wet = open('wet.pkl','rb')
wet = pickle.load(wet)
dry = open('dry.pkl','rb')
dry = pickle.load(dry)

GF1314 = open('GF_1314.pkl','rb')
GF1314 = pickle.load(GF1314)

GF1315 = open('GF_1315.pkl','rb')
GF1315 = pickle.load(GF1315)

GF1316 = open('GF_1316.pkl','rb')
GF1316 = pickle.load(GF1316)


In [8]:
np.shape(EOF1)


(114, 88)

In [10]:
import numpy.ma as ma
#spatial correlation
a = np.reshape(EOF1,114*88)
b = np.reshape(wet,114*88)
c = np.reshape(dry,114*88)


In [12]:
print(ma.corrcoef(ma.masked_invalid(a),ma.masked_invalid(b)))

[[1.0 0.8502618473729345]
 [0.8502618473729345 1.0]]


In [13]:
print(ma.corrcoef(ma.masked_invalid(a),ma.masked_invalid(c)))

[[1.0 -0.8778325322052863]
 [-0.8778325322052863 1.0]]


In [15]:
import numpy.ma as ma
#spatial correlation
a = np.reshape(EOF1,114*88)
b = np.reshape(GF1314,114*88)
c = np.reshape(GF1315,114*88)
d = np.reshape(GF1316,114*88)


In [16]:
print(ma.corrcoef(ma.masked_invalid(a),ma.masked_invalid(b)))

[[1.0 0.2877838530440774]
 [0.2877838530440774 1.0]]


In [17]:
print(ma.corrcoef(ma.masked_invalid(a),ma.masked_invalid(c)))

[[1.0 0.7110571913327326]
 [0.7110571913327326 1.0]]


In [18]:
print(ma.corrcoef(ma.masked_invalid(a),ma.masked_invalid(d)))

[[1.0 0.6755020463673037]
 [0.6755020463673037 1.0]]
